services:
  mapbox-polygons-client:
    build: 
      context: ./mapbox-polygons-client  # Path to your React application
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose React app on port 3000
    depends_on:
      - mapbox-polygons-server 

  mapbox-polygons-server:
    build: 
      context: ./mapbox-polygons-server
      dockerfile: Dockerfile
    depends_on:
      - mssql
    environment:
      - DB_HOST=mssql
      - DB_USER=sa
      - DB_PASSWORD=Str0ngPass!2025
      - DB_SERVER=localhost
      - DB_DATABASE=Mapbox
      - JWT_SECRET=vois_map_box_secret_key
      - JWT_EXPIRES_IN=12h
      - PORT=3000

  mssql:
    image: mcr.microsoft.com/mssql/server:latest  # Use the latest MSSQL image
    environment:
      # Set MSSQL environment variables (refer to MSSQL documentation)
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngPass!2025 
    ports:
      - "1433:1433"  # Expose MSSQL on port 1433

volumes:
  mssql-data:  # Optional: Persist MSSQL data