services:
  mapbox-polygons-client:
    build: 
      context: ./mapbox-polygons-client 
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    environment:
      - VITE_HOST=0.0.0.0
    depends_on:
      - mapbox-polygons-server 

  mapbox-polygons-server:
    build: 
      context: ./mapbox-polygons-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mapbox-polygons-mssql
    environment:
      - DB_HOST=mapbox-polygons-mssql
      - DB_USER=sa
      - DB_PASSWORD=Str0ngPass!2025
      - DB_DATABASE=Mapbox
      - JWT_SECRET=vois_map_box_secret_key
      - JWT_EXPIRES_IN=12h
      - PORT=3000

  mapbox-polygons-mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngPass!2025 
    ports:
      - "1433:1433"  

volumes:
  mssql-data: 